name: Fetch SILSO daily (Sunspot-Daily)

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC; change if desired
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        env:
          # Optional overrides:
          # TARGET_FILENAME: Sunspot-Daily   # script will append .csv if missing
          # ARCHIVE_DIR: data/archive
          # SILSO_URL: https://www.sidc.be/silso/INFO/sndtotcsv.php
        run: python scripts/fetch_silso.py

      - name: Commit and push new data (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Stage the target and archive (if used)
          git add data/Sunspot-Daily.csv || true
          git add data/archive || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(data): update Sunspot-Daily for $(date -u +%Y-%m-%d)"
          git push
